---
title: Ikawka
description: Life would have been easier, if I have the source code.
disqus_shortname: ikawkablog
reading_time: true
words_per_minute: 200
logo: images/logo.png
excerpt_separator: <!-- more -->
url: https://ikawka.github.io
menu:
- title: Home
  url: /
- title: Tags
  url: /tags
- title: Categories
  url: /categories
  type: categories
- title: Disclaimer
  url: /disclaimer

owner:
  name: Amiel Simbahon
  site: https://ikawka.github.io
  avatar: images/avatar.jpg
  bio: Software Maker
  email: pixelazion@gmail.com
  twitter: ikawka
  github: ikawka
twitter:
social:
- title: github
  url: https://github.com/ikawka
- title: linkedin
  url: https://www.linkedin.com/in/amiel-simbahon-b108671a/
- title: youtube
  url: https://www.youtube.com/channel/UCAp5fQNEmR62OIvYxraFrzw
background:
google_analytics: UA-92313979-1
google_verify: _U6meTS7aL1bWc5P46uO0n48m-g4f3yf2xgKiqJ_68o
bing_verify:
timezone: America/New_York
locale: en_US
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
paginate: 5
float_share: true
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
include:
- .htaccess
exclude:
- demo/*
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- '*.sublime-project'
- '*.sublime-workspace'
- test
- spec
- Gruntfile.js
- package.json
- node_modules
gems:
- jekyll-paginate
- jekyll-sitemap
#- jekyll-admin
theme: jekyll-theme-cayman
