title:            Ikawka
description:      Life would have been easier, if I have the source code.

disqus_shortname: ikawkablog
reading_time:     true
words_per_minute: 200
logo: images/logo.png

excerpt_separator: <!-- more -->
url: https://ikawka.github.io

menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Disclaimer'
    url: '/disclaimer'
  # - title: 'Favorites'
  #   url: '#'
  #   submenu:
  #     - title: 'Code Highlighter'
  #       url: '/intro/code-highlighting-post/'
  #     - title: 'Sample Post'
  #       url: '/intro/sample-post/'
owner:
  name:           Amiel Simbahon
  site:           https://ikawka.github.io
  avatar:         images/avatar.jpg
  bio:            "Software Maker"
  email:          pixelazion@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: ikawka # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: ikawka

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/ikawka"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/amiel-simbahon-b108671a/"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCAp5fQNEmR62OIvYxraFrzw"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-92313979-1
google_verify: _U6meTS7aL1bWc5P46uO0n48m-g4f3yf2xgKiqJ_68o
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate, jekyll-sitemap, jekyll-admin]

theme: jekyll-theme-cayman
